### ISSUE TITLE
AE 2018 Crash

### ISSUE THREAD

**Issue by YarlBoro** [baku89/ISF4AE#1]
First, let me thank You for creating and sharing GLSLCanvas!

I've tried it with two versions of After Effects. 
AE CC 2017.2 (14.2.1.34) - loads and renders some of shaders from Book of Shaders that I've tried. So far no crashes, performance is ok (just a little choppiness while adjusting parameters in plug-in UI).

AE CC 2018 (15.0.0, build 180) - after attempting to load shader via "Load Shader.." AE crashes, same if I just add GLSLCanvas to empty solid and move playhead. Few times it even froze my whole system (not a kernel panic, just complete freeze and lots of artefacts). I also tried to change AE renderer from Metal to Software Only, same thing.
Crash report:
[AE_2018_GLSLCanvas_CRASH.txt](https://github.com/baku89/glslCanvas4AE/files/1591318/AE_2018_GLSLCanvas_CRASH.txt)

I've compiled Your plugin on MacOS 10.12.6 & XCode 9.2 (9C40b) and used latest AE SDK.

**Comment by baku89** [comment]
Thank you for reporting the bug.
I just released the beta for AE 2022, so please try it on your environment!
https://github.com/baku89/ISF4AE/releases/tag/v0.1.1
