### ISSUE TITLE
Crash when long TYPE does not have LABELS or VALUES field defined.

### ISSUE THREAD

**Issue by gmatters** [baku89/ISF4AE#22]
The ISF spec says long "has" the extra LABELS and VALUES fields, but does not explicitly state whether they are required or optional.

ISF4AE in both renderISFToCPUBuffer and UpdateParamsUI assume that LABELS and VALUES exist for every long, and AE will crash if those fields are not defined for a long.

ISF Editor has logic to use values as labels if there is no LABELS field (or LABELS size mismatches), and values between MIN and MAX if there is no VALUES field defined. See [ISFEditor/ISFEditor_app/misc_ui/ISFUIItem.cpp](https://github.com/mrRay/VVISF-GL/blob/96b00da11e4497da304041ea2a5ffc6e3a8c9454/examples/Qt/ISFEditor/ISFEditor_app/misc_ui/ISFUIItem.cpp#L110)

The ISF Editor behaviour allows long to be used a generic integer input. At least, ISF4AE should fail to load rather than crash.

**Comment by gmatters** [comment]
For repro, here is the Auto Color Tune.fs with the colorCount field redefined to use MIN and MAX instead of VALUES and LABELS

[Auto_Color_Tone__missing_labels.fs.zip](https://github.com/baku89/ISF4AE/files/12414499/Auto_Color_Tone__missing_labels.fs.zip)

**Comment by baku89** [comment]
Thanks to @gmatters's PR, the issue has been completely solved;)
